services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Nee@7483
      MYSQL_DATABASE: task
    ports:
      - "2046:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-react-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pNee@7483"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: springboot
    image: task-backend:latest
    ports:
      - "2047:2005"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-react-network

  frontend:
    container_name: react
    image: task-frontend:latest
    ports:
      - "2048:80"
    depends_on:
      - backend
    networks:
      - springboot-react-network

# Declare volumes for persistence
volumes:
  mysql-data:

# Define custom bridge network
networks:
  springboot-react-network:
 