services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Nee@7483
      MYSQL_DATABASE: task
    ports:
      - "2047:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net
  healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pNee@7483"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    image: neeraj2005/task-backend:latest
    container_name: springboot
    ports:
      - "2040:2005"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: neeraj2005/task-frontend:latest
    container_name: react
    ports:
      - "2048:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net: